language: node_js
node_js:
  - '9.11'

cache:
  directories:
    - "node_modules"

script:
  - npm run build
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  on:
    branch: master