export const FIND_WORDS_IN_PHOTO = 'FIND WORDS IN PHOTO';
export const FIND_WORDS_IN_PHOTO_SUCCESS = 'FIND WORDS IN PHOTO SUCCESS';
export const FIND_WORDS_IN_PHOTO_FAILURE = 'FIND WORDS IN PHOTO FAILURE';
